### ISSUE TITLE
Array with nodes that have attributes AND values

### ISSUE THREAD

**Issue by sandino** [gatkin/declxml#11]
Hello,

I have an XML of a structure:

```
<categories>
    <category parentId="" id="000000001" order="1" tagid="">Red</category>
    <category parentId="000000001" id="000000002" order="1" tagid="">Blue</category>
    <category parentId="000000002" id="000000254" order="1" tagid="">Green</category>
</categories>
```

So, you see, it's an array of dictionaries.

Could you please give me a hint how to parse such data?

**Comment by gatkin** [comment]
declxml supports a small subset of XPath syntax. Specifically, the dot selector ('.') can be used here to select the current element which allows you to select multiple values from a single element both from its attributes and its element data.

So a processor that would work for your sample data would be

```python
import declxml as xml

processor = xml.array(xml.dictionary('category', [
    xml.string('.', attribute='parentId', required=False),
    xml.string('.', attribute='id'),
    xml.string('.', attribute='order'),
    xml.string('.', attribute='tagid', required=False),
    xml.string('.', alias='color'),
]), nested='categories')
```

Specifically, the line `xml.string('.', alias='color')` means "From the current dictionary element (category in this case) select its data and store it in a field called color in the resulting dictionary".

I hope that helps. Please let me know if you have any more questions or issues.

**Comment by gatkin** [comment]
Closing this as resolved for now. Definitely let me know if you have any more issues or questions!

**Comment by sandino** [comment]
@gatkin That works, thank you a lot for exhaustive explanation!

And sorry for late response.
